"""name change from f to p

Revision ID: 522311bd5658
Revises: 
Create Date: 2022-10-04 21:10:12.735346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522311bd5658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.String(length=10000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('folder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbols', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('portfolio')
    # ### end Alembic commands ###
